### ISSUE TITLE
Empty values for 'expo' property

### ISSUE THREAD

**Issue by ruester** [GFZ-Centre-for-Early-Warning/assetmaster#3]
With commit 2a8677d the GeoPackage file now has some empty values for the 'expo' property (for example for 'Casa Blanca').
That is why currently the `assetmaster.py` script returns an error:

```
# python3 assetmaster.py -71.8 -71.4 -33.2 -33.0 SARA_v1.0 res intersects
Traceback (most recent call last):
  File "assetmaster.py", line 283, in <module>
    Main.create_with_arg_parser().run()
  File "assetmaster.py", line 226, in run
    self._write_outputs()
  File "assetmaster.py", line 173, in _write_outputs
    self.dicts,self.taxonomies)
  File "assetmaster.py", line 162, in _exportNrml05
    xml_string = nrml.write_nrml05_expo(dataframe,metadata,dicts,taxonomies,filename)
  File "/usr/share/git/assetmaster/expo_nrml.py", line 135, in write_nrml05_expo
    geocell = pd.DataFrame(json.loads(item.expo))
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by maxpittore** [comment]
fixed with this [commit ](https://github.com/GFZ-Centre-for-Early-Warning/assetmaster/commit/9edea45dce312d67b04623dff2a2068d04e7d7b5#diff-84942813b0fa4b27ca78cb7752c9bc32)
